from django.conf.urls import url
from . import views
from django.views import static

STATICFILES_DIRS = (
    'C:/inetpub/wwwroot/wxedu8.23/api/static'
)

urlpatterns = [
        url(r'^static/(?P<path>.*)$',static.serve,{'document_root':STATICFILES_DIRS,'show_indexes': True}),
        url(r'^openid/$',views.getOpenid),
        url(r'^getteacherinf/(?P<tphone>[0-9]+)$',views.getteacherinf),
        url(r'^getstudentinf/(?P<sphone>[0-9]+)$',views.getstudentinf),
        url(r'^getteacherrelease/(?P<tphone>[0-9]+)$',views.RETeacher_list_tphone),
        url(r'^getstudentrelease/(?P<sphone>[0-9]+)$',views.RETeacher_list_sphone),
        url(r'^registeredteachers/(?P<id>[0-9]+)$', views.RETeacher_list_id),
        url(r'^registeredstudents/(?P<id>[0-9]+)$', views.REStudent_list_id),
        url(r'^registeredteachers/sub/(?P<sub>[0-9]+)$', views.RETeacher_list_sub),
        url(r'^registeredstudents/sub/(?P<sub>[0-9]+)$', views.REStudent_list_sub),
        url(r'^grade/$',views.subject_list),
        url(r'^login/$',views.islogin),
        url(r'^appoint/$',views.appoint_add),
        url(r'^message/$', views.message_add),
        url(r'^getsappoint/(?P<tphone>[0-9]+)/(?P<state>[0-9]+)$',views.get_s_appoint),
        url(r'^gettappoint/(?P<sphone>[0-9]+)/(?P<state>[0-9]+)$',views.get_t_appoint),
        url(r'^commentadd/$',views.comment_add),
        url(r'^deletereleasebyid/$',views.deletereleasebyid),
        url(r'^csname/$',views.csname_list),
        url(r'^teacheraddrelease/$',views.teacheraddrelease),
        url(r'^studentaddrelease/$',views.studentaddrelease),
        url(r'^register/$',views.register),
        url(r'^appointaccept/(?P<id>[0-9]+)$',views.appoint_accept),
        url(r'^appointrefuse/(?P<id>[0-9]+)$',views.appoint_refuse),
        url(r'^appointpay/(?P<id>[0-9]+)$',views.appoint_pay),
        url(r'^appointfinish/(?P<id>[0-9]+)$',views.appoint_finish),
        url(r'^appoint/(?P<id>[0-9]+)$',views.get_appoint_by_id),
        url(r'^cancelmsg/$',views.cancelmsg),
        url(r'^refundadd/(?P<id>[0-9]+)$',views.refund_add),
        url(r'^refundaccept/(?P<id>[0-9]+)$',views.refund_accept),
        url(r'^refundrefuse/(?P<id>[0-9]+)$',views.refund_refuse),
        url(r'^getnewmsg/$',views.getnewmsg),
        url(r'^getoldmsg/$',views.getoldmsg),
        url(r'^readmsg/(?P<id>[0-9]+)$',views.readmsg),
        url(r'^selectbyname/$',views.selectbyname),
        url(r'^getcomment/$',views.get_comment),
        url(r'^timage/$',views.t_image),
        url(r'^simage/$',views.s_image),
        url(r'^loginbymsg/$',views.loginbymsg),
        url(r'^forgetpsd/$',views.forgetpsd),
        url(r'^gethotsubject/$',views.gethotsubject),
        url(r'^pay/$',views.pay_jsapi),
        url(r'^enterprisepay/$',views.enterprise_pay),
        url(r'^gethotteacher/$',views.get_hot_teacher),
        url(r'^searchsubject/$',views.searchSubject),
        url(r'^updatecharacter/$',views.updateCharacter),
        url(r'^updatecity/$',views.updateCity),
        url(r'^updategender/$',views.updateGender),
        url(r'^updateintroduction/$',views.updateIntroduction),
        url(r'^updatename/$',views.updateName),
        url(r'^updatetgrade/$',views.updateTGrade),
        url(r'^updatesgrade/$',views.updateSGrade),
        url(r'^updateeducation/$',views.updateEducation),
        url(r'^updatemajor/$',views.updateMajor),
        url(r'^updateaddress/$',views.updateAddress),
        url(r'^getfivecharacter/$',views.getFiveCharacter),
        url(r'^retest/$',views.retest),
        
    ]
